spring:
  application:
    name: ula-api-gateway
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
zuul:
  ribbon:
    eager-load:
      enabled: true
  semaphore:
    max-semaphores: 500
  sensitive-headers:
    - Authorization,Cookie,Set-Cookie
  routes:
    ula-auth-service: /api/v1/auth/**
    ula-university-service: /api/v1/university/**
    ula-faculty-service: /api/v1/faculty/**
    ula-student-service: /api/v1/student/**
    ula-exam-service: /api/v1/exam/**
    ula-static-content-service: /storage/**
  host:
    connect-timeout-millis: 60000

