spring:
  application:
    name: ula-discovery

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
